language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.3.0
sudo: false
cache: bundler
before_install:
  - "echo 'gem: --no-ri --no-rdoc --no-document' > ~/.gemrc"
install:
  - "bundle install --jobs=3 --retry=3 --without=noci --path=${BUNDLE_PATH:-vendor/bundle}"
