---
nick: hwping
server: irc.freenode.net
port: 6667
channels:
  - launcher-test
auth_nicks: # the bot reacts only to those nicks
  - nick1
  - nick2
targets:
  nick1:
    - 200 # right ms
    - 300 # top ms
  nick2:
    - 500 # right ms
    - 800 # top ms
